// <auto-generated />
using FitnessTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819140924_addInitialDb")]
    partial class addInitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            MuscleGroup = "biceps"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            MuscleGroup = "Tricep"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            MuscleGroup = "shoulder"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            MuscleGroup = "legs"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            MuscleGroup = "Back"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
